// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQscrpTcaBJnsIUxAUGbmbj4Fak4uRZK8',
    appId: '1:766652088817:web:9919991c981dce91b34450',
    messagingSenderId: '766652088817',
    projectId: 'ecomm-af340',
    authDomain: 'ecomm-af340.firebaseapp.com',
    storageBucket: 'ecomm-af340.firebasestorage.app',
    measurementId: 'G-85851L22PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbgcQuww4N0D6Kl5HXgT0gpg_uQ-7AVjA',
    appId: '1:766652088817:android:8d822ff65c57fb4fb34450',
    messagingSenderId: '766652088817',
    projectId: 'ecomm-af340',
    storageBucket: 'ecomm-af340.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt5WaYRLn2dupmNpMYlYO_K0zj46sxRZY',
    appId: '1:766652088817:ios:5076471abf7fffa2b34450',
    messagingSenderId: '766652088817',
    projectId: 'ecomm-af340',
    storageBucket: 'ecomm-af340.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );
}
